"""Add image column to vegetables

Revision ID: 9f3a76a9aae1
Revises: 
Create Date: 2025-02-26 21:12:37.603026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f3a76a9aae1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vegetables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vegetables', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
